### ISSUE TITLE
Why I can not convert my ANN model to SNN successfully?

### ISSUE THREAD

**Issue by oxygenman** [NeuromorphicProcessorProject/snn_toolbox#10]
The attach file is the model of ANN I use. The architecture of the model is shown below. But when I performing the converting program, it failed with the err：
![model](https://user-images.githubusercontent.com/28856502/29356768-ea149378-82a7-11e7-8498-f06f1e0785f3.png)
<img width="563" alt="2017-08-16 4 58 41" src="https://user-images.githubusercontent.com/28856502/29356821-1ecfbeda-82a8-11e7-9fa6-17eb20283dce.png">
[model.zip](https://github.com/NeuromorphicProcessorProject/snn_toolbox/files/1227710/model.zip)

It seems my model have an "InputLayer" that the toolbox can't understand, how can I solve this problem?

**Comment by rbodo** [comment]
I can't download your model.zip (GitHub says "Page not found"). Could you email it to me? Thanks

**Comment by rbodo** [comment]
Nope, still not working: I can't extract the model.zip. File seems to be damaged. Please send it by email. Thanks.

**Comment by rbodo** [comment]
Fixed this bug (it was due to the branching directly after the input layer). 

However, there seems to be a problem with the final MaxPool layer (the other Pooling layers work fine). Replacing Max by AveragePool also works. I will get back to you with a solution hopefully soon.

**Comment by oxygenman** [comment]
OK，thank you very much, I will keep learning your code!

**Comment by rbodo** [comment]
OK, all good now. The problem was using data_format 'channels_last' instead of 'channels_first'. Both are now supported. I tested your model with random input and it ran fine.
