### ISSUE TITLE
How do I get the BRIAN2 model of the converted SNN

### ISSUE THREAD

**Issue by nishraptor** [NeuromorphicProcessorProject/snn_toolbox#106]
I want to convert the example pytorch ANN to an SNN, and get the brian model (not to run it). I then want to extract the connectivity of the entire network. How would I go about doing this?

**Comment by rbodo** [comment]
I'd start by modifying [this example script for pytorch](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/master/examples/mnist_pytorch_INI.py) to use the brian backend, as in [this example](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/master/examples/mnist_keras_brian2.py). If the scripts work for you with MNIST, then insert your dataset and model.

If using Brian via PyNN, the connections are saved automatically as text files, see [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/a85ada7b5d060500703285ef8a68f06ea1ffda65/snntoolbox/simulation/target_simulators/pyNN_target_sim.py#L237).

With Brian2, check out [this implementation](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/a85ada7b5d060500703285ef8a68f06ea1ffda65/snntoolbox/simulation/target_simulators/brian2_target_sim.py#L245) for saving the weights.
