### ISSUE TITLE
when I run the example of Bineraynet,I recieve the error message:IndexError: too many indices for array

### ISSUE THREAD

**Issue by oxygenman** [NeuromorphicProcessorProject/snn_toolbox#11]
<img width="762" alt="2017-11-13 9 02 48" src="https://user-images.githubusercontent.com/28856502/32727053-1cb082e8-c8b6-11e7-8ec9-74c021436878.png">

**Comment by rbodo** [comment]
Did you modify the config file for this experiment? If so, please post it here. I can't reproduce this error with the current settings and the most recent version of the toolbox. What version are you using? Pip or repo? I recommend updating to the latest version of the repo. Let me know if there are still issues then. Thanks
