### ISSUE TITLE
custom layers objects

### ISSUE THREAD

**Issue by balodhi** [NeuromorphicProcessorProject/snn_toolbox#112]
Can you please explain the structure of JSON file used for customer layer objects ?
I am trying to convert a custom model which has custom layers. I want to add those layers for conversion.

**Comment by rbodo** [comment]
Not sure what JSON file you are referring to. But maybe this helps: https://github.com/NeuromorphicProcessorProject/snn_toolbox/issues/111#issuecomment-943455416
