### ISSUE TITLE
Questions about the converted weights

### ISSUE THREAD

**Issue by xiaoyuehai** [NeuromorphicProcessorProject/snn_toolbox#116]
I am confused about the weights after converting ANN, for example when my convolution layer parameters are (inp=1, outp=32, kernel_size=(3,3)), so the number of ANN parameters should be 320 under the condition of adding bias, but the size of SNN after conversion is 215168 and is 1 dimensional, so how should I use it, is it related to my simulator (Brain2)？

**Comment by rbodo** [comment]
In Brian2, there is no direct support for weight sharing as in convolutions. So the conv layers need to be "unrolled" into fully-connected layers, which implies copying of the kernels, hence the increased number of parameters and single dimension.
