### ISSUE TITLE
NCHW format not supported in temporal_mean_rate_tensorflow.py

### ISSUE THREAD

**Issue by Hpotato0** [NeuromorphicProcessorProject/snn_toolbox#117]
Hello, I was working with snn_toolbox to convert keras models of nchw format to spiking neural networks, and I found out the function max_pool_with_argmax only accepts 'NHWC' as its data format.

at line 833 of temporal_mean_rate_tensorflow.py:
```
_, max_idxs = tf.nn.max_pool_with_argmax(
            self.mem_input, self.pool_size, self.strides, self.padding.upper(),
            conv_utils.convert_data_format(self.data_format, 4),
            include_batch_in_index=True)
```

Fetching and converting the data format here brings out an error if the data format is NCHW, and manual permutation of the axes is needed to make this work with NCHW.

**Comment by rbodo** [comment]
Yes, that is a known limitation from using the tensorflow maxpool function. #103
