### ISSUE TITLE
Failed to run mnist_keras_loihi example

### ISSUE THREAD

**Issue by Rashedape** [NeuromorphicProcessorProject/snn_toolbox#118]
Hello, 
I tried to run the github example after the installation of SNN_toolbox. The example (mnist_keras_INI) works fine but i failed to run the mnist_keras_loihi example. It showed an error "No module named 'nxsdk_modules_ncl'". It would be great if anyone can help me.

Thank You.

**Comment by rbodo** [comment]
#100
