### ISSUE TITLE
Error to run mnist_keras_loihi example

### ISSUE THREAD

**Issue by Rashedape** [NeuromorphicProcessorProject/snn_toolbox#119]
Hello,

After installing snn_toolbox i tried to run mnist_keras_loihi example from [https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/master/examples/mnist_keras_loihi.py](url)  into my INRC cloud account. During the spiking Model compilation it shows 
**Trying to load board from /homes/rashedul/snn_toolbox/temp_rashedul/log/gui/test/model_dumps/runnables.
Could not load board.**

Moreover, sometimes it connects to the backend server  and terminates the job with the following message. 
**INFO:HST:  srun: Force Terminated job 1487479
INFO:HST:  srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
INFO:HST:  slurmstepd: error: *** STEP 1487479.0 ON ncl-ext-ghrd-03 CANCELLED AT 2022-06-07T13:20:42 DUE TO TIME LIMIT ***
INFO:DRV:      Executing...................Error 1206.55s
INFO:HST:  srun: error: ncl-ext-ghrd-03: task 0: Terminated**

 Sometimes it not even able to connect to the back end server and terminates the job with the following error message. 

**TypeError: 'NoneType' object is not subscriptable**

Entire error message is attached for both scenarios.
[Example.zip](https://github.com/NeuromorphicProcessorProject/snn_toolbox/files/8856513/Example.zip)

 
Thank You.

**Comment by rbodo** [comment]
Hi,

For the TypeError, please see [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/issues/111#issuecomment-974400782).

The job termination due to time limit is a deadlock issue that has irregularly appeared before without clear cause. You could try changing the Loihi partition you are running the job on.

**Comment by Rashedape** [comment]
Hi rbodo,
I tried the Loihi partition and it worked. Thank you.
