### ISSUE TITLE
How to save PyNN projections and How they can be used for SpiNNaker?

### ISSUE THREAD

**Issue by aitsam12** [NeuromorphicProcessorProject/snn_toolbox#120]
Q1) I am running the SNN toolbox with brian2 simulator. I want to save to projections so I can use them for spiNNaker.
Can you tell me the complete process to do that? 

Q2) I tried using nest simulator but it is giving the following error:
ValueError: `off_grid_spiking` is a readonly kernel parameter

My config file:

# Generate Config file
config = configparser.ConfigParser()
config['paths'] = {
    'path_wd': WORKING_DIR,
    'dataset_path': DATASET_DIR,
    'filename_ann': MODEL_NAME,
    'runlabel': MODEL_NAME+'_'+str(NUM_STEPS_PER_SAMPLE)
}
config['tools'] = {
    'evaluate_ann': True,
    'parse': True,
    'normalize': True,
    'simulate': True
}
#'INI', 'spiNNaker'
config['simulation'] = {
    'simulator': 'nest',
    'duration': NUM_STEPS_PER_SAMPLE,
    'num_to_test': NUM_TEST_SAMPLES,
    'batch_size': BATCH_SIZE,
    'keras_backend': 'tensorflow'
}
config['output'] = {
    'verbose': 1,
    'plot_vars': {
        'input_image',
        'spiketrains',
        'spikerates',
        'spikecounts',
        'operations',
        'normalization_activations',
        'activations',
        'correlation',
        'v_mem',
        'error_t'
    },
    'overwrite': True
}
# Write the configuration file
config_filepath = os.path.join(WORKING_DIR, 'config')
with open(config_filepath, 'w') as configfile:
    config.write(configfile)
################################################################################
# Convert the model using SNNToolbox
if CONVERT_MODEL:
    main(config_filepath)

**Comment by rbodo** [comment]
Hi, please take a look at #67 regarding saving projections. As for the other issue, a full stack trace would be necessary, but I'll most likely not be able to help as I have currently no way of debugging this pipeline.
