### ISSUE TITLE
ONNX model could not be ported to Keras.Mismatched elements 100%

### ISSUE THREAD

**Issue by unlemon** [NeuromorphicProcessorProject/snn_toolbox#130]
I encounter an issue when trying to convert a pretrained Pytorch Alexnet model to SNN. I read the code and found that pytorch_input_lib.py is used to convert Pytorch model to Keras model. But the error comes up as below:
![image](https://user-images.githubusercontent.com/33743268/191406478-9b31f3b8-57a3-4825-a9f8-d1edf2a76de2.png)
What should I do?  Thanks!

**Comment by rbodo** [comment]
You should be able to fix the error by adding ZeroPadding layers as suggested in the console output.

Please see also this related issue: #96
