### ISSUE TITLE
Energy and runtime estimation for running the SNN on neuromorphic simulator

### ISSUE THREAD

**Issue by shreshth-29** [NeuromorphicProcessorProject/snn_toolbox#139]
From what I understand, the results are obtained on a neuromorphic simulator (INI for example). It gives the performance metrics, but I was wondering if there was a way to obtain the energy consumption, inference time and the no. of MACC operations as well?

**Comment by rbodo** [comment]
Hi, for the INI simulator, you also get the number of MACC operations, but not energy consumption or inference time because the simulation runs on a GPU and does not reflect truly asynchronous processing on dedicated hardware. See also #70 for an explanation of the logged data.

**Comment by shreshth-29** [comment]
Thanks for the reply! Now for the snn , we get 'operations' and not 'mac'
operations. Are these all accumulate operations or multiply and accumulate?

**Comment by rbodo** [comment]
only accumulate ops in the SNN.
