### ISSUE TITLE
Error when run the LeNet5 example

### ISSUE THREAD

**Issue by ljxgit** [NeuromorphicProcessorProject/snn_toolbox#14]
I run the LeNet example in Keras, the command is "snntoolbox -t ./examples/models/lenet5/keras/config", and there is an error, "AttributeError: 'Conv2D' object has no attribute '_inbound_nodes'"
Could you give me some suggestions? Thank you very much! @rbodo

**Comment by rbodo** [comment]
Hi Ijxgit, I guess you are using an older version of keras. Please upgrade keras to version 2.0.6. (Unfortunately the examples are not yet compatible with the most recent version of keras.)

**Comment by ljxgit** [comment]
Hi, rbodo, I have upgrade the Keras to version 2.0.6, but there is also this error, **"snntoolbox\conversion\utils.py, line 151, in normalize_parameters
    input_layer = layer._inbound_nodes[0].inbound_layers[0].name
AttributeError: 'Conv2D' object has no attribute '_inbound_nodes'",**
does the version of Tensorflow has some constraints?? Thanks, please give me some suggestion
