### ISSUE TITLE
AveragePooling2D.__init__() missing 1 required positional argument: 'pool_size'

### ISSUE THREAD

**Issue by bjourne** [NeuromorphicProcessorProject/snn_toolbox#145]
The `mnist_keras_nest.py` produces this error. I guess `pool_size=2` should be given as argument.

**Comment by rbodo** [comment]
Hi bjourne,

The toolbox hasn't been actively maintained for some time now and is likely not compatible with newer dependency versions.

An old list of dependencies can be found [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/issues/17). Versions up until at least 2021 should also still work.

**Comment by bjourne** [comment]
Thanks for the reply. I didn't know the software was unmaintained. Perhaps it should be mentioned.
