### ISSUE TITLE
Gui code small bug

### ISSUE THREAD

**Issue by PanYicheng** [NeuromorphicProcessorProject/snn_toolbox#19]
I think the code in 'snntoolbox/bin/gui/gui.py' line 1512 has a small bug,
`os.path.join(os.path.dirname(__file__),
                                                      '..', '..','snntoolbox'
                                                      'config_defaults')`, here the 3rd string 'snntoolbox' should not be included because the path is used relatively. After removing it, I can run the gui without error.

**Comment by rbodo** [comment]
Hi PanYichen, thanks for the catch. We have not worked on the GUI for over a year, so it will be quite out of sync with the rest of the toolbox. I would expect to run into more errors. Using the toolbox from terminal is recommended. But you are of course welcome to bring the GUI up to date and submit a pull request!
