### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by MingjieLiu** [NeuromorphicProcessorProject/snn_toolbox#24]
hi, when I run the example of Inceptionv3, it show RecursionError as I wrote in the title
All the parameters I set followed the examples
I also change the data_format to channels_first

**Comment by rbodo** [comment]
Please try again after updating the toolbox to the latest version of the repo. Commit 4d8643b9002f2014d6f9feb931ec3a1fa393f06c should have solved this.

**Comment by MingjieLiu** [comment]
It can work now. 
Thank you.
