### ISSUE TITLE
cifar10 cnn_BN.py running on 'nest'

### ISSUE THREAD

**Issue by piewchee** [NeuromorphicProcessorProject/snn_toolbox#30]
Hi Bodo,

I trained 'cnn_BN,py" model without BIAS and using AveragePooling2D. The accuracy is 82.65.h5
with gcn and zca=False,
I regenerated the x_norm.npz using "cifar10.py" with gca and zca=False.
I checked the normalisation weight distribution plots for both INI and nest. They are similar.

When I run  using 20 samples on INI simulator. the accuracy is 90%; but when using nest
simulator the accuracy is at chance level (10%). For nest simulator, I used  "reset by subtraction" too.
The scale factor for "poisson rate" of input layer is changed from 1000 to 2000 and cell Vthres = 0.75; in order to match the average spiking rate comparable to INI (0.03 per sim. time step).
May I know why is the error so high and what other parameters can I tune?
Attached are the Pearson and Total spike counts.

**Comment by rbodo** [comment]
The reset_by_subtraction is only implemented on INIsim, we cannot expect to see an effect in Nest.

I did not receive any attachments.

You should be aware that you are entering more or less uncharted territory here - simulating a large network for CIFAR10 on Nest is not trivial or guaranteed to work at all. So figuring this out is a research question that goes beyond technical support with the toolbox. But if you can show me the correlation plots and activity maps I can have a look and try to make sure that there is no obvious bug.

**Comment by piewchee** [comment]
Hi Bodo,
Sorry. The PC acting on me again, I can't attach file in my previous mail. Here are the activity and Pearson plots.
![pearson_nest](https://user-images.githubusercontent.com/31268312/53461189-b2b2e380-3a7a-11e9-8f9b-fce67615d532.png)
![activity_distribution_nest](https://user-images.githubusercontent.com/31268312/53461195-bc3c4b80-3a7a-11e9-9647-f9f9ff886662.png)

**Comment by rbodo** [comment]
Hi Del, I'm looking into it. Will hopefully have an update for you next week. Please also have a look at #25 , could be related.

**Comment by piewchee** [comment]
Hi Bodo,
Thanks!.  Actually I am using Keras 2.1.6.
By the way, I noticed that main problem could be due to "Reset to zero".
If I change INI config to "Reset to zero", the inference accuracy will be bad too.
As nest neuron model doesn't allowed "reset by subtraction", I am looking at 
how to create a new neuron model in Spinnaker to accept "reset by subtraction"
to verify if its helps.
Rgds
Del

**Comment by rbodo** [comment]
Good idea. That would be a really cool enhancement!

**Comment by rbodo** [comment]
Hi Del,

Were you able to solve this, perhaps by implementing "reset by subtraction"? I'm closing this for now but feel free to reopen if there is an update.

Thanks

**Comment by piewchee** [comment]
Hi Bodo,

Yes I did try but it doesn’t help.

Anyway another problem is that we only have one Spinnaker board.
We encountered serious packet drop issue due to back pressure.
This may add on to the problem too.

Best Regards
Del
