### ISSUE TITLE
Possible Issue Setting Convolutional Biases

### ISSUE THREAD

**Issue by wilkieolin** [NeuromorphicProcessorProject/snn_toolbox#45]
https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/f5877ed6d270839fa1e42baf0f96c2c8f074f0a6/snntoolbox/simulation/utils.py#L1165

I believe that to properly set the biases for the correct groups of feature maps, this line should be as follows:

```i_offset[i * n:(i + 1) * n] = biases[i]```

**Comment by rbodo** [comment]
That's right, thanks for pointing out this error. You're welcome to submit a pull request if you like, otherwise I'll try to upload a patch in the next two weeks.
