### ISSUE TITLE
Attribute error: sequential model has no loss function

### ISSUE THREAD

**Issue by roshan-gopalakrishnan** [NeuromorphicProcessorProject/snn_toolbox#49]
I am training a custom dataset using Keras on GPU and uses categorical cross entropy. I am using keras multi GPU datagenerator function to load the data from sub directories. While conversion, SNN toolbox is showing Attribute error: sequential model has no loss function. Could you help me ? Is that due to datagenerator function ? Should I load the dataset similar to MNIST or CIFAR-10 examples ?

**Comment by rbodo** [comment]
The datagenerator should work fine in SNN toolbox, I've used it regularly for ImageNet and other datasets.

Do you get the same error also under different conditions (e.g. using one of the example scripts)? I would need to see more details to be able to help with this (error stack trace, network architecture / training script).

**Comment by delpie** [comment]
Hi Bodo,

Roshan and I are in the same team. 
We are able to run the Keras trained .h5 model in snntoolbox using INI.
However we encountered an error during weight normalisation. Wonder what
happpend. Below is the message: Rgds Del
Building parsed model...

Compiling parsed model...

Normalizing parameters...
Traceback (most recent call last):
  File "/home1/ncp/anaconda2/bin/snntoolbox", line 11, in <module>
    sys.exit(main())
  File "/home1/ncp/anaconda2/lib/python2.7/site-packages/snntoolbox/bin/run.py", line 50, in main
    test_full(config)
  File "/home1/ncp/anaconda2/lib/python2.7/site-packages/snntoolbox/bin/utils.py", line 95, in test_full
    normalize_parameters(parsed_model, config, **normset)
  File "/home1/ncp/anaconda2/lib/python2.7/site-packages/snntoolbox/conversion/utils.py", line 147, in normalize_parameters
    scale_fac = scale_facs[layer.name]
KeyError: '00Conv2D_64x64x16'

**Comment by rbodo** [comment]
Hmm, the toolbox tries to load scale factors from a previous run from disk, to save computation time. If the user changed the network architecture in the same working directory, it can lead to a mismatch with the saved dict. Try deleting the ``normalization`` folder in your working dir.
