### ISSUE TITLE
Missing nxsdk_modules for Loihi backend

### ISSUE THREAD

**Issue by CreateRandom** [NeuromorphicProcessorProject/snn_toolbox#54]
Hello,

we would like to be able to deploy a converted spiking model to Loihi on Intel NCL. When specifiying the correct backend, we however get: `ImportError: No module named 'nxsdk_modules'`. We tested nxsdk 0.8.5 and 0.9, both exhibiting the same behaviour. It seems related to this commit: 495714a8799029160d83c0a8c58cd01e9f3b9731, where the Loihi-related code was removed and the import was added. Where can we obtain the correct module to be able to run on loihi? Thanks for your help.

**Comment by rbodo** [comment]
Hi, 

From your description I understand you are an INRC member and have access to the nxsdk repo. Then you should find the ``nxsdk_modules`` directly beneath the source dir ``nxsdk``. Unless they have been moved recently (I only had access till October). In that case you should ask INRC support to update the import statement.

**Comment by CreateRandom** [comment]
Hi,

I'm not sure where this folder is located (if it still exists), but I solved this problem regardless. In the installation instructions provided to our group, reference is made to the folder /nfs/ncl/releases. Each subfolder contains nxsdk as a tarball and another tar file (called nxdsk-apps) - which in turn also contains the modules we were hunting for. Consequently, we can now run the simulation. I'm not well-versed enough in the history of either NXSDK or the toolbox to really understand whether anything has changed in this respect, so let me know if I should get in touch with the INRC support or whether that's not necessary.

**Comment by rbodo** [comment]
Glad to hear you found it. No need to contact INRC support then.
