### ISSUE TITLE
Loihi simulator parameters

### ISSUE THREAD

**Issue by CreateRandom** [NeuromorphicProcessorProject/snn_toolbox#55]
Hello,
 
to use the toolbox on Loihi, one needs to pass a 'loihi' entry in the config dict for the main method. We have reverse-engineered what needs to go in there, but are not sure about some of the settings.

```
loihi_config_dict = {
    # nWB has a maximum of 8
    # weightExponent must be 0 anyway
    'connection_kwargs': {'numWeightBits': 8, 'weightExponent': 0},
    # vThMant: no idea how to set this, max is 2 ** 17 - 1
    # biasExp must be 6 anyway
    'compartment_kwargs': {'vThMant': 2 ** 8, 'biasExp': 6},
    # no clue how to set this
    'desired_threshold_to_input_ratio': 1
} 
```

There seems to be very little documentation on these hyperparameters. Could you possibly give us some details on what exactly they do and reasonable default settings we could use?

Best,

Klaus

**Comment by rbodo** [comment]
The nxtf module in ``nxsdk_modules`` should contain a ``tutorials`` directory with example scripts for using the toolbox with loihi as backend. You should find default values and some more description of these parameters there.

**Comment by rbodo** [comment]
Another place to look at is the NxSDK documentation, section
SDK modules >> DNN >> SNN Toolbox Configuration >> Loihi backend for SNN-Toolbox
