### ISSUE TITLE
tensorflow.keras

### ISSUE THREAD

**Issue by utouto97** [NeuromorphicProcessorProject/snn_toolbox#58]
I've got error shown below.

`
TypeError: __init__() got an unexpected keyword argument 'ragged'
`

I'm guessing this error happened due to the difference of original keras and tensorflow.keras.

Is it possible use tensorflow.keras?

**Comment by rbodo** [comment]
That's likely (would need a bit more info than this one line to be able to say more).

I put a note in the [installation instructions](https://snntoolbox.readthedocs.io/en/latest/guide/installation.html) for keras / tf versions that are confirmed to work.

**Comment by utouto97** [comment]
When I run `snntoolbox.bin.run.main` from python3, the error happened.
The ann model has been trained with `from tensorflow import keras`.

Ubuntu 18.04
Python 3.6.9
snntoolbox==0.4.1
tensorflow==2.0.1
Keras==2.3.0

config file
```
[paths]
path_wd = ./
dataset_path = %(path_wd)s
filename_ann = model
```

**Comment by utouto97** [comment]
Applying tf_keras.patch solved this problem.
Thanks.
