### ISSUE TITLE
How to measure run time of simulation

### ISSUE THREAD

**Issue by RKCZ** [NeuromorphicProcessorProject/snn_toolbox#62]
Hi,
what would be the right way to measure how long does a simulation run in real time? Is it possible to measure it?

**Comment by rbodo** [comment]
You mean for instance a simulation using the default INIsim? 

You could just place a timeit around [this line](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/2cd4ca6dc541b568f4d508542fa2cc79a58e5e68/snntoolbox/simulation/utils.py#L601):

``` python
import time
start_time = time.time()
output_b_l_t = self.simulate(**data_batch_kwargs)
end_time = time.time()
time_per_batch = end_time - start_time
```

That gives you the time to run one batch, but includes some post-processing of the result and recorded states (spikes, membrane potentials etc), if so specified in your config. 

To get a more fine-grained measurement, time the actual call to the predict method [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/2cd4ca6dc541b568f4d508542fa2cc79a58e5e68/snntoolbox/simulation/target_simulators/INI_temporal_mean_rate_target_sim.py#L166), which will give you the wall clock time it takes to process one time step in rate-based INIsim. 

Just be aware that these measurements are of limited value as this particular simulator is not really optimized for SNNs; each time step is basically a forward pass of the network on a GPU/CPU. It would be more interesting to time a simulator that's based on an actual SNN emulation framework like Brian or Nest, or of course using SNN hardware like SpiNNaker and Loihi.

**Comment by RKCZ** [comment]
Thank you for the advice, I measured the batch time as you hinted me.
