### ISSUE TITLE
Question about using on snn toolbox

### ISSUE THREAD

**Issue by lchunleo** [NeuromorphicProcessorProject/snn_toolbox#64]
Hi 

 i am new to spiking neural network. i noted that your toolbox is converting existing dnn implementation into spiking network to be run in the gpu as simulator prior into the spiking chip. is it possible to use in the gpu for real work instead of just a simulator? thank you

**Comment by rbodo** [comment]
Hi,

I'm not quite sure what you mean with "real work". The simulation running on the GPU is real in the sense that it has the features of the SNN you are modelling - membrane potentials, spikes, reset, refractory period, leak, etc. The GPU implementation does not suffer from some of the constraints of neuromorphic hardware, like limited number of connections, neurons, state memory, etc. That can be an advantage or a disadvantage depending on how realistic you want your simulation to be (which depends on the specific accelerator you are targeting). Some of the constraints of neuromorphic hardware (like limited numeric precision) can be emulated in the toolbox to some extent. Finally, the GPU implementation is not as optimized for running asynchronous models as neuromorphic hardware can be. But it allows running far bigger models than what has been demonstrated so far on dedicated hardware.

So it really depends on what you are looking for.

**Comment by lchunleo** [comment]
thanks for the detailed info. just to clarify my "real work" definition is to using the SNN to do detection or classification tasks instead of being just a simulator for its eventual deploying to SNN chip.

**Comment by rbodo** [comment]
Ah ok. Yes, by default the toolbox performs classification with your converted model.
