### ISSUE TITLE
The accuracy of RESNET network training is high in Ann, but low in SNN

### ISSUE THREAD

**Issue by wusaifei** [NeuromorphicProcessorProject/snn_toolbox#66]
Hello, the toolbox is very easy to use, very good!
I encountered a little problem. Cifar10 is selected as the data set，and Using keras_ INI.  I used Resnet18 to train ANN network, and the accuracy rate was as high as 95% (with some tricks), but after using ANN to convert to SNN, the accuracy rate of SNN was only 48%. I guess the reason is that there is no conversion in the add part of Resnet module. But I look at the author's snntoolbox.parsing.utils There is' Add 'in it. What's wrong with me?

**Comment by zenmar** [comment]
Hi @wusaifei , did you find a solution to your problem?
Thanks!
