### ISSUE TITLE
multi bits spike trains need reset by modulo?

### ISSUE THREAD

**Issue by wusaifei** [NeuromorphicProcessorProject/snn_toolbox#68]
Using the  given by MNIST_ keras_ INI.py How to start multi bit training? Now I only know how to modify other parameters such as' reset by module '?Look forward to your reply！

**Comment by wusaifei** [comment]
Apart from the need to modify 'reset': 'reset by module', is there any other place that needs to be modified, because I only modified this place and found that its accuracy rate is much lower than 'reset':'reset by subsection '.
@rbodo @duguyue100 @pabogdan @ej159

**Comment by rbodo** [comment]
Not sure I understand your question. The toolbox does not do "multi bit training". Reset by modulo is an experimental feature and not guaranteed to work better than reset by subtraction.

**Comment by wusaifei** [comment]
@rbodo Thanks for the author's reply, I read through the code and found that it only supports 1 Bi output of 0 and 1.
