### ISSUE TITLE
How to load and simulate an INI model saved in a .h5

### ISSUE THREAD

**Issue by joaromi** [NeuromorphicProcessorProject/snn_toolbox#69]
In the run_pipeline() function, the converted model is saved in a .h5 file. Is it possible to load and simulate it again in INI (with the _tensorflow_ backend)? 

I tried something like what is written below and did not work. The 'load' function requires me to install _theano_. However, it was not necessary when I ran the Toolbox before as I chose the _tensorflow_ backend in the 'config' file.

SNN = SNN(config)
SNN.load(path_wd, model_name + '_INI')     # <--- Error here

data_batch_kwargs = {}
data_batch_kwargs['truth_b'] = np.argmax(np.array(testset['y_test'].flatten()))
data_batch_kwargs['x_b_l'] = testset['x_test']
results = SNN.simulate(**data_batch_kwargs)

**Comment by joaromi** [comment]
I forgot to mention that the config file is set with:
'simulator': 'INI' ;  'keras_backend': 'tensorflow' ;  'spike_code': 'temporal_mean_rate'

And I imported the SNN class as:
from snntoolbox.simulation.target_simulators.INI_temporal_mean_rate_target_sim import SNN

**Comment by rbodo** [comment]
Hi,

I was not able to reproduce this issue. Please check your error stack trace to see where the theano import gets called.

**Comment by rbodo** [comment]
Unrelated to the error you are getting, if you want to load and run a previously saved SNN, you will have to apply a small hack:

The ``SpikeLayer`` initializer expects to receive the configparser object as a keyword argument. I have not yet implemented it for loading, so for now you'd have to load the config manually like so: 

After [this line](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/f358f8f33ce8cfe1296c3f3e34830d0666bdc57c/snntoolbox/simulation/backends/inisim/temporal_mean_rate_tensorflow.py#L37), add the following:

```
if self.config is None:
    from snntoolbox.bin.utils import load_config
    self.config = load_config('<log_dir_of_current_run>/.config')
```

In your log dir, look for a hidden file called ``.config``. This file is created by the toolbox during setup of your conversion run, and contains all configuration parameters (including the default values not explicitly specified in your config file). Insert the path to this file in the line above.

You may also need to replace [this line](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/f358f8f33ce8cfe1296c3f3e34830d0666bdc57c/snntoolbox/simulation/backends/inisim/temporal_mean_rate_tensorflow.py#L524) with

``kwargs.pop(str('config'), None)``

With these changes, I was able to load the converted SNN.

If you happen to implement a proper way of specifying the path to the .config file in the constructor, you are welcome to submit a pull request! (Note also that there is already a load function stub [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/f358f8f33ce8cfe1296c3f3e34830d0666bdc57c/snntoolbox/simulation/target_simulators/INI_temporal_mean_rate_target_sim.py#L244).)
