### ISSUE TITLE
Loading SNN on Loihi

### ISSUE THREAD

**Issue by keeperbitz** [NeuromorphicProcessorProject/snn_toolbox#75]
Hello,

Using TF 2.3.1, NxSDK 0.9.5, and the most recent SNN-TB and nx_backend.py dev. versions, I am successfully able to convert DNNs to SNNs and run them on Intel Loihi. A challenge arises when I attempt to load already converted SNNs. I get the following error when running CIFAR-10 example on Loihi:

AttributeError                            Traceback (most recent call last)
<ipython-input-19-a0671e984746> in <module>
      1 os.environ["SLURM"] = "1"
      2 model = build_snn_from_file(snntb_log_dir=MODEL_NAME+"_"+reset_mode,
----> 3                             num_steps_per_img=num_steps_per_sample)

<ipython-input-16-356234f79699> in build_snn_from_file(snntb_log_dir, num_steps_per_img)
     21         filepath=model_path,
     22         customObjects=None,
---> 23         logdir=abs_log_dir)
     24 

~/apps-snntb-ncl/nxsdk_modules/dnn/src/dnn_layers.py in loadNxModel(filepath, customObjects, doCompile, **kwargs)
   3135         model.storeAllCandidates = kwargs['storeAllCandidates']
   3136 
-> 3137     model.initialize()
   3138 
   3139     return model

AttributeError: 'Functional' object has no attribute 'initialize'

I was wondering if this may be an issue related to TF 2.3.1? Is there a workaround?

**Comment by rbodo** [comment]
This error appears probably because the tutorial tries to load a model that has been saved with a much older software setup. I'm able to use the loadNxModel function just fine with a new model. So a workaround would be to train the CIFAR model from scratch (if possible not on the VM, as stated in cell 7 of the tutorial). If you get it to work that way, please submit a PR for the updated model (I'm currently on vacation and can't do it myself).

**Comment by keeperbitz** [comment]
Thanks Bodo.

I have not been able to nail down why this is happening. I am using my personal example as well, and if I convert the model then run on Loihi in one script, it works fine, with loadNxModel loading the model as a NxModel type. However, if I convert in one run, then re-run the script in another run without conversion, trying to use the saved NxModel.h5 type, the model gets loaded as a tensorflow.python.keras.engine.functional.Functional object instead of a NxModel, throwing this initialize error. I will keep working on my end to debug why this may be the case.

**Comment by keeperbitz** [comment]
Update: The issue seems specific to TF 2.3.1. I do not have this problem with TF 2.2.0.
