### ISSUE TITLE
Kapoho Bay Integration

### ISSUE THREAD

**Issue by keeperbitz** [NeuromorphicProcessorProject/snn_toolbox#77]
Hello,

Has SNN-TB been validated to work on the Kapoho Bay backend?

Thanks,

KB

**Comment by rbodo** [comment]
I have not done it myself, but I can't think of a reason why it shouldn't work there.

**Comment by keeperbitz** [comment]
This can be closed. I ran into Jupyter issue with the tutorials, but after moving to Python script, I have validated it to work on Kapoho Bay.
