### ISSUE TITLE
Issue while creating a csv file.

### ISSUE THREAD

**Issue by ssaphale** [NeuromorphicProcessorProject/snn_toolbox#78]
I'm trying to create csv file for the MIT BIH dataset using the following code.

from IPython.display import display
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import os
import shutil
import csv
import wfdb
import scipy as sp
from wfdb import processing
from scipy import signal
import heartpy as hp

name = (100,101)

with open('MIT-BIH10.csv','w') as t1:
    writer = csv.writer(t1, delimiter=',',lineterminator='\n')
    for file in name:
        sig,record = wfdb.rdsamp(recordname = str(file))
        annotation = wfdb.rdann(recordname = str(file), extension='atr')

**I'm getting and error cannot unpack non-iterable Record object at sig, record = wfdb.rdsamp(recordname= str(file))** 
it was working completely fine for 2 days but now the issue is srising what might be the problem. Please help.

**Comment by rbodo** [comment]
Sorry, this is not related to SNN toolbox.
