### ISSUE TITLE
Keyerror

### ISSUE THREAD

**Issue by mightyabra** [NeuromorphicProcessorProject/snn_toolbox#82]
I am trying out an example code in the SNN Toolbox and I keep getting a key error. Below is the code and error message. Thank you.

"""End-to-end example for SNN Toolbox.
This script sets up a small CNN using Keras and tensorflow, trains it for one
epoch on MNIST, stores model and dataset in a temporary folder on disk, creates
a configuration file for SNN toolbox, and finally calls the main function of
SNN toolbox to convert the trained ANN to an SNN and run it using Brian2
simulator.
"""

import os
import time
import numpy as np

from tensorflow import keras
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Conv2D, AveragePooling2D, Flatten, Dense, \
    Dropout, BatchNormalization, Activation
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
#import configparser
from snntoolbox.bin.run import main
from snntoolbox.utils.utils import import_configparser

# WORKING DIRECTORY #
#####################

# Define path where model and output files will be stored.
# The user is responsible for cleaning up this temporary directory.
path_wd = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(
    'might')), '..', 'mighty', str(time.time())))
os.makedirs(path_wd)

# GET DATASET #
###############

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize input so we can train ANN with it.
# Will be converted back to integers for SNN layer.
x_train = x_train / 255
x_test = x_test / 255

# Add a channel dimension.
axis = 1 if keras.backend.image_data_format() == 'channels_first' else -1
x_train = np.expand_dims(x_train, axis)
x_test = np.expand_dims(x_test, axis)

# One-hot encode target vectors.
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Save dataset so SNN toolbox can find it.
np.savez_compressed(os.path.join(path_wd, 'x_test'), x_test)
np.savez_compressed(os.path.join(path_wd, 'y_test'), y_test)
# SNN toolbox will not do any training, but we save a subset of the training
# set so the toolbox can use it when normalizing the network parameters.
np.savez_compressed(os.path.join(path_wd, 'x_norm'), x_train[::10])

# CREATE ANN #
##############

# This section creates a simple CNN using Keras, and trains it
# with backpropagation. There are no spikes involved at this point.

input_shape = x_train.shape[1:]
input_layer = Input(input_shape)

layer = Conv2D(filters=16,
               kernel_size=(5, 5),
               strides=(2, 2))(input_layer)
layer = BatchNormalization(axis=axis)(layer)
layer = Activation('relu')(layer)
layer = Conv2D(filters=32,
               kernel_size=(3, 3),
               activation='relu')(layer)
layer = AveragePooling2D()(layer)
layer = Conv2D(filters=8,
               kernel_size=(3, 3),
               padding='same',
               activation='relu', )(layer)
layer = Flatten()(layer)
layer = Dropout(0.01)(layer)
layer = Dense(units=10,
              activation='softmax')(layer)

model = Model(input_layer, layer)

model.summary()

model.compile('adam', 'categorical_crossentropy', ['accuracy'])

# Train model with backprop.
model.fit(x_train, y_train, batch_size=64, epochs=1, verbose=2,
          validation_data=(x_test, y_test))

# Store model so SNN Toolbox can find it.
model_name = 'mnist_cnn'
keras.models.save_model(model, os.path.join(path_wd, model_name + '.h5'))

# SNN TOOLBOX CONFIGURATION #
#############################

# Create a config file with experimental setup for SNN Toolbox.
configparser = import_configparser()
config = configparser.ConfigParser()
#print(os.path.join(path_wd, model_name))
#print(config.read(os.path.join(os.getcwd(), 'config.ini')))
config['paths'] = {
    'path_wd': path_wd,             # Path to model.
    'dataset_path': path_wd,        # Path to dataset.
    'filename_ann': model_name     # Name of input model.
}

config['tools'] = {
    'evaluate_ann': True,           # Test ANN on dataset before conversion.
    'normalize': True,              # Normalize weights for full dynamic range.
}

config['simulation'] = {
    'simulator': 'brian2',          # Chooses execution backend of SNN toolbox.
    'duration': 50,                 # Number of time steps to run each sample.
    'num_to_test': 5,               # How many test samples to run.
    'batch_size': 1,                # Batch size for simulation.
    'dt': 0.1                       # Time resolution for ODE solving.
}

config['input'] = {
    'poisson_input': False          # Images are encodes as spike trains.
}

config['output'] = {
    'plot_vars': {                  # Various plots (slows down simulation).
        'spiketrains',              # Leave section empty to turn off plots.
        'spikerates',
        'activations',
        'correlation',
        'v_mem',
        'error_t'}
}

# Store config file.
config_filepath = os.path.join(path_wd, 'config')
with open(config_filepath, 'w') as configfile:
    config.write(configfile)

# RUN SNN TOOLBOX #
###################

main(config_filepath)

#################################Error Message############################################
Evaluating input model on 5 samples...
Top-1 accuracy: 100.00%
Top-5 accuracy: 100.00%

Parsing input model...
Skipping layer InputLayer.
Parsing layer Conv2D.
Using activation relu.
Parsing layer AveragePooling2D.
Skipping layer BatchNormalizationV1.
Skipping layer Activation.
Parsing layer Conv2D.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-0aedb0275f68> in <module>
    149 ###################
    150 
--> 151 main(config_filepath)

f:\anaconda3\envs\spike\lib\site-packages\snntoolbox\bin\run.py in main(filepath)
     29     if filepath is not None:
     30         config = update_setup(filepath)
---> 31         run_pipeline(config)
     32         return
     33 

f:\anaconda3\envs\spike\lib\site-packages\snntoolbox\bin\utils.py in run_pipeline(config, queue)
     86         print("Parsing input model...")
     87         model_parser = model_lib.ModelParser(input_model['model'], config)
---> 88         model_parser.parse()
     89         parsed_model = model_parser.build_parsed_model()
     90 

f:\anaconda3\envs\spike\lib\site-packages\snntoolbox\parsing\utils.py in parse(self)
    203                 inserted_flatten = False
    204             else:
--> 205                 inbound = self.get_inbound_names(layer, name_map)
    206 
    207             attributes = self.initialize_attributes(layer)

f:\anaconda3\envs\spike\lib\site-packages\snntoolbox\parsing\utils.py in get_inbound_names(self, layer, name_map)
    364             return ['input']
    365         else:
--> 366             inb_idxs = [name_map[str(id(inb))] for inb in inbound]
    367             return [self._layer_list[i]['name'] for i in inb_idxs]
    368 

f:\anaconda3\envs\spike\lib\site-packages\snntoolbox\parsing\utils.py in <listcomp>(.0)
    364             return ['input']
    365         else:
--> 366             inb_idxs = [name_map[str(id(inb))] for inb in inbound]
    367             return [self._layer_list[i]['name'] for i in inb_idxs]
    368 

KeyError: '2460047621984'

**Comment by mightyabra** [comment]
I have installed snntoolbox-0.5.0

**Comment by rbodo** [comment]
Please use the development version from github, and latest tensorflow. 
Let me know if the error persists.

**Comment by mightyabra** [comment]
> Please use the development version from github, and latest tensorflow.
> Let me know if the error persists.

Thanks rbodo.

I installed the lastest tensorflow and git installed the development version of snntoolbox but then, I kept getting an error with tensorflow (ImportError: cannot import name 'convert_kernel' from tensorflow.python.keras.something). So, I installed a lower version of tensorflow-gpu (version 1.15.4).

Now its working. Thanks
