### ISSUE TITLE
have a error when loaded my CNN model

### ISSUE THREAD

**Issue by Lizhanying-Sudo** [NeuromorphicProcessorProject/snn_toolbox#85]
hello,Bodo 

I try to use your example (mnist_keras_brian2.py) in toolbox  to classify eeg data(2 classes).

- data shape: _(122-1000-3)_   =>  sapmle-signal-channel

If use a larger conv2D filters, i will receive a error:

`ERROR      Brian 2 encountered an unexpected error. If you think this is a bug in Brian 2, please report this issue either to the discourse forum at <http://brian.discourse.group/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: C:\Users\LZY\AppData\Local\Temp\brian_debug_b4ngwfoe.log  Additionally, you can also include a copy of the script that was run, available at: C:\Users\LZY\AppData\Local\Temp\brian_script_sqe_qfy7.py Thanks! [brian2]
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\SNNtoolbox\lib\site-packages\brian2\synapses\synapses.py", line 1407, in connect
    self._add_synapses_from_arrays(i, j, n, p, namespace=namespace)
  File "D:\ProgramData\Anaconda3\envs\SNNtoolbox\lib\site-packages\brian2\synapses\synapses.py", line 1547, in _add_synapses_from_arrays
    group_name=group.name))
IndexError: The given target indices contain values outside of the range [0, 13503] allowed for the target group "neurongroup_1"`

If I don't have a clear description, please tell me.
Thanks for your helping!

**Comment by rbodo** [comment]
Hi Lizhanzing-Sudo,

I'm sorry, I won't be able to offer technical support any more.

Hope you find the issue.

Best

**Comment by rbodo** [comment]
On second thought, if you send me your architecture, I can quickly try to reproduce the error, maybe I see something on first glance.
