### ISSUE TITLE
SNNtoolbox release version no longer compatible with keras

### ISSUE THREAD

**Issue by HeatPhoenix** [NeuromorphicProcessorProject/snn_toolbox#87]
While trying to run any of the examples (ex. mnist_keras_nest.py) in SNN toolbox, it'll error out on importing 'convert_kernel' from keras. 

`ImportError: cannot import name 'convert_kernel' from 'tensorflow.python.keras.utils.conv_utils' (/home/<user>/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/conv_utils.py)`

Now, the reason for this (and you already fixed this in the development version) is that Keras moved that function from that file. This dev repo already has a fix for it, but the stable release does not. Might be useful (and save time of end-users) to either note that the stable version will not work with the keras/tensorflow backend or simply update the release?

Installing the repo using `pip install .` in the snn_toolbox folder and then running the examples works flawlessly, however.

_(Feel free to close this issue if this isn't relevant to the team, just ran into this today and had to spend some time figuring it out)_

**Comment by rbodo** [comment]
Thanks for reporting this. Will update the release shortly.
