### ISSUE TITLE
Spike Coding

### ISSUE THREAD

**Issue by zenmar** [NeuromorphicProcessorProject/snn_toolbox#93]
Hi,

I'm trying to understand the dataflow after converting the ANN to the SNN.
I was expecting to see some encoding of the dataset (i.e. rate-encoding/ttfs), and as far as I understood, the toolbox uses rate-encoding.
Somehow, I can't seem to find where the encoding happens?
And, is it possible to use the toolbox with different spike-coding?

Thanks in advance!

Cheers

**Comment by rbodo** [comment]
By default, the toolbox encodes input values with a regular firing rate, which is equivalent to injecting constant currents into the neurons of the input layer. This is what's being done [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/1f1addab4caed15a63f416f40e8f983e05c23638/snntoolbox/simulation/target_simulators/INI_temporal_mean_rate_target_sim.py#L168). Alternatively, one can use a Poisson encoding, which is just a noisier version of the rate encoding, as implemented [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/1f1addab4caed15a63f416f40e8f983e05c23638/snntoolbox/simulation/target_simulators/INI_temporal_mean_rate_target_sim.py#L156). Also, the toolbox supports [input spikes from an event sensor](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/1f1addab4caed15a63f416f40e8f983e05c23638/snntoolbox/simulation/target_simulators/INI_temporal_mean_rate_target_sim.py#L158) like the DVS.

You can of course add your own input encoding at this point in the code.
