### ISSUE TITLE
Hello, I tried to run the toolbox code with gpu, but it didn't work. I want to ask how your code supports gpu?

### ISSUE THREAD

**Issue by RPDS2020** [NeuromorphicProcessorProject/snn_toolbox#94]
Hello, I tried to run the toolbox code with gpu, but it didn't work. I want to ask how your code supports gpu?

**Comment by rbodo** [comment]
The toolbox is built on top of Keras/Tensorflow. So please check that you are able to run a model on the GPU outside of the toolbox using TF. If you then still think there is an issue with the toolbox, please post a specific error description.

**Comment by RPDS2020** [comment]
Sorry to bother you again!The tensorflow-gpu and keras-gpu versions I installed used GPU acceleration while testing other code to run, but when using your toolbox came up: "WARNING:tensorflow:AutoGraph could Not transform <bound method SpikeLayer.init_Neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3c07f923c8> and will run it as-is."At the same time, GPU acceleration was not used during the simulation.Do you know what the cause of this bug is?If you are interested, please help me, thank you! ：）

**Comment by RPDS2020** [comment]
I tried to solve it online, but it didn't work. I guess it might be a problem with snntoolbox code？ This is the error output:
2021-05-28 20:50:54.803818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:08:00.0 name: Tesla V100-DGXS-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2021-05-28 20:50:54.803874: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-05-28 20:50:54.803902: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-05-28 20:50:54.803929: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-05-28 20:50:54.803957: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-05-28 20:50:54.803983: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-05-28 20:50:54.804009: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-05-28 20:50:54.804035: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-05-28 20:50:54.808648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-05-28 20:50:54.808702: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-05-28 20:50:54.977231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-28 20:50:54.977282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2021-05-28 20:50:54.977301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2021-05-28 20:50:54.985363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30588 MB memory) -> physical GPU (device: 0, name: Tesla V100-DGXS-32GB, pci bus id: 0000:08:00.0, compute capability: 7.0)
2021-05-28 20:50:54.988641: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ebed0d82e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-05-28 20:50:54.988672: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-DGXS-32GB, Compute Capability 7.0
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3afbfa7438>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:From /home/yhchen_jsjxy/anaconda3/envs/GP3.6/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1786: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3af14b8be0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3b83f1d7f0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3afbf99f28>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3b53fa1f98>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeAveragePooling2D object at 0x2b3b83f1d400>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3afbfd3be0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3b83f1c860>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3b83f5f780>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3afbfd35c0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3c07e9c550>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeAveragePooling2D object at 0x2b3b83f69cc0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3b83f6c240>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3c07e80ba8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3b83e3a160>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3b83f93278>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3b83f34400>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3b83e6c860>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3c07ea4828>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3b83f34c18>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3c07f37898>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeAveragePooling2D object at 0x2b3c07eecd68>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3c07f923c8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3c07f38f98>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3c87e2c6a0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3c07f8af60>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3c87e89978>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3c87e33be0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3c87ef1c50>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3c87e96eb8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3c87f4fcc0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeAveragePooling2D object at 0x2b3c87ef19b0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3c87fa87f0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3c87f4fbe0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3d1ae44a90>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3c87fa8550>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3d1aea4d68>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3d1ae4cf60>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3d1af11080>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3d1aea4ac8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3d1af6f0f0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeAveragePooling2D object at 0x2b3d1af05da0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3d1afcfda0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeDense object at 0x2b3d1af78748>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3d1b03be10>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeDense object at 0x2b3d1afcf898>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3d1b0a62e8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: expected an indented block (<unknown>, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeDense object at 0x2b3d1b04e048>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.

**Comment by RPDS2020** [comment]
I tried to solve it online, but it didn't work. I guess it might be a problem with snntoolbox code？ This is the error output:
2021-05-28 20:50:54.803818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:08:00.0 name: Tesla V100-DGXS-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2021-05-28 20:50:54.803874: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-05-28 20:50:54.803902: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-05-28 20:50:54.803929: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-05-28 20:50:54.803957: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-05-28 20:50:54.803983: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-05-28 20:50:54.804009: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-05-28 20:50:54.804035: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-05-28 20:50:54.808648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-05-28 20:50:54.808702: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-05-28 20:50:54.977231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-28 20:50:54.977282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] 0
2021-05-28 20:50:54.977301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0: N
2021-05-28 20:50:54.985363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30588 MB memory) -> physical GPU (device: 0, name: Tesla V100-DGXS-32GB, pci bus id: 0000:08:00.0, compute capability: 7.0)
2021-05-28 20:50:54.988641: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ebed0d82e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-05-28 20:50:54.988672: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Tesla V100-DGXS-32GB, Compute Capability 7.0
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3afbfa7438>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output.
Cause: expected an indented block (, line 39)
WARNING:tensorflow:From /home/yhchen_jsjxy/anaconda3/envs/GP3.6/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1786: calling BaseResourceVariable.init (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3af14b8be0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output.
Cause: expected an indented block (, line 27)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.init_neurons of <tensorflow.python.eager.function.TfMethodTarget object at 0x2b3b83f1d7f0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output.
Cause: expected an indented block (, line 39)
WARNING:tensorflow:AutoGraph could not transform <bound method SpikeLayer.get_new_mem of <snntoolbox.simulation.backends.inisim.temporal_mean_rate_tensorflow.SpikeConv2D object at 0x2b3afbf99f28>> and will run it as-is.

**Comment by rbodo** [comment]
Which TF version are you using?

I don't have access to a GPU at the moment so I cannot help debugging now.

You might try to disable graph mode (i.e. comment out the tf.function decorators)
