### ISSUE TITLE
Reuse converted model, different inputs?

### ISSUE THREAD

**Issue by zenmar** [NeuromorphicProcessorProject/snn_toolbox#95]
Hi,

First, thanks for the ongoing support and the package in general!

I would like to know if it's possible after initial conversion, to rerun the resulting SNN with new data/images? 
(i.e., use the SNN as a black-box model / function)
Also, could you please explain me how to read-out the outputs (i.e. classification results on inference), as a way to use them further?

Sorry for these basic questions!

Thank you

**Comment by rbodo** [comment]
Hi,

If by rerunning you mean loading the converted SNN (a Keras .h5 file), then please have a look at [this issue](https://github.com/NeuromorphicProcessorProject/snn_toolbox/issues/69#issuecomment-719576784). In short, it should be possible with a small hack.

Aside from the technical aspect, there is the parameter normalization algorithm to consider. If you've enabled normalization during conversion (as is recommended), then the toolbox will have used a subset of your original data to scale the weights in each layer using a percentile of the measured activity distribution. The purpose of this normalization is to prevent vanishing and saturating spikerates during inference. If you apply the SNN later on new data, the weights may not be scaled optimally, depending on how different activation statistics are for the new data.

As for your second question, the network output can be accessed in the [code here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/1f1addab4caed15a63f416f40e8f983e05c23638/snntoolbox/simulation/target_simulators/INI_temporal_mean_rate_target_sim.py#L168). But perhaps the [logging features](https://github.com/NeuromorphicProcessorProject/snn_toolbox/issues/70#issuecomment-719614501) may also be of use.
